# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FifoClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for InstagramClone
  	pod 'Firebase/Analytics'
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Storage'
	pod 'SDWebImage', '~> 5.0'

  # Pods for FifoClient

end
